version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - dealit-network
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8085:8085"
    networks:
      - dealit-network

networks:
  dealit-network:
    driver: bridge
